<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>9.0</Version>
    <PackageId>Simple.dotNet.Core</PackageId>
    <Authors>jarvis</Authors>
    <Product>Simple.dotNet</Product>
    <RepositoryType>git</RepositoryType>
    <AssemblyName>Simple.dotNet.Core</AssemblyName>
    <RootNamespace>Simple.Core</RootNamespace>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://github.com/jarvisph/Simple.git</RepositoryUrl>
    <PackageTags>dotnet core;</PackageTags>
    <Description>添加扩展方法</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SensitiveWord\COVID-19词库.txt" />
    <None Remove="SensitiveWord\GFW补充词库.txt" />
    <None Remove="SensitiveWord\其他词库.txt" />
    <None Remove="SensitiveWord\反动词库.txt" />
    <None Remove="SensitiveWord\广告类型.txt" />
    <None Remove="SensitiveWord\政治类型.txt" />
    <None Remove="SensitiveWord\新思想启蒙.txt" />
    <None Remove="SensitiveWord\暴恐词库.txt" />
    <None Remove="SensitiveWord\民生词库.txt" />
    <None Remove="SensitiveWord\涉枪涉爆.txt" />
    <None Remove="SensitiveWord\网易前端过滤敏感词库.txt" />
    <None Remove="SensitiveWord\色情类型.txt" />
    <None Remove="SensitiveWord\色情词库.txt" />
    <None Remove="SensitiveWord\补充词库.txt" />
    <None Remove="SensitiveWord\贪腐词库.txt" />
    <None Remove="SensitiveWord\零时-Tencent.txt" />
    <None Remove="SensitiveWord\非法网址.txt" />
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="SensitiveWord\COVID-19词库.txt" />
    <EmbeddedResource Include="SensitiveWord\GFW补充词库.txt" />
    <EmbeddedResource Include="SensitiveWord\其他词库.txt" />
    <EmbeddedResource Include="SensitiveWord\反动词库.txt" />
    <EmbeddedResource Include="SensitiveWord\广告类型.txt" />
    <EmbeddedResource Include="SensitiveWord\政治类型.txt" />
    <EmbeddedResource Include="SensitiveWord\新思想启蒙.txt" />
    <EmbeddedResource Include="SensitiveWord\暴恐词库.txt" />
    <EmbeddedResource Include="SensitiveWord\民生词库.txt" />
    <EmbeddedResource Include="SensitiveWord\涉枪涉爆.txt" />
    <EmbeddedResource Include="SensitiveWord\网易前端过滤敏感词库.txt" />
    <EmbeddedResource Include="SensitiveWord\色情类型.txt" />
    <EmbeddedResource Include="SensitiveWord\色情词库.txt" />
    <EmbeddedResource Include="SensitiveWord\补充词库.txt" />
    <EmbeddedResource Include="SensitiveWord\贪腐词库.txt" />
    <EmbeddedResource Include="SensitiveWord\零时-Tencent.txt" />
    <EmbeddedResource Include="SensitiveWord\非法网址.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GoogleAuthenticator" Version="3.3.0-beta1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.15" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.15" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.15" />
    <PackageReference Include="System.Reflection.DispatchProxy" Version="4.8.2" />
    <PackageReference Include="ToolGood.Words" Version="3.1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
